---
title: "Amazon Descriptive Analysis by Data-Cated"
author: "Eirik, Jillian, Nancy, Yifan, Ziyu "
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: yes
  # pdf_document: 
  #   latex_engine: xelatex
  
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
	fig.width = 8.5,
	message = FALSE,
	warning = FALSE,
	# include = FALSE,
	echo = FALSE
)

options(tinytex.verbose = TRUE)

# Clear environment of variables and functions
rm(list = ls(all = TRUE)) 

# Clear environment of packages
if(is.null(sessionInfo()$otherPkgs) == FALSE) {
  lapply(paste("package:", names(sessionInfo()$otherPkgs), sep=""), 
         detach, character.only = TRUE, unload = TRUE)
}
```


# Install and load Packages

```{r, warning=FALSE, message=FALSE, echo=TRUE}
library(tidyverse)
library(skimr)
library(sqldf)
library(gridExtra)
library(fpp2)
library(olsrr)
library(GGally)
library(lubridate)

```


# Load Data

```{r, warning=FALSE, message=FALSE, echo=TRUE}

adoption <- read.csv(file = "../RawData/adoption_final.csv", header=TRUE, sep=",")
april <- read.csv(file = "../RawData/april_billing_final.csv", header=TRUE, sep=",")
may <- read.csv(file = "../RawData/may_billing_final.csv", header=TRUE, sep=",")
june <- read.csv(file = "../RawData/june_billing_final.csv", header=TRUE, sep=",")

```



```{r}
adoption$Geo_Code <- as.character(adoption$Geo_Code)
adoption$Customer_size <- as.factor(adoption$Customer_size)
adoption$Visualize <- as.factor(adoption$Visualize)
adoption$Alert <- as.factor(adoption$Alert)
adoption$Report <- as.factor(adoption$Report)   
adoption$Month <- as.factor(adoption$Month)
adoption$Customer_ID <- as.factor(adoption$Customer_ID)
summary(adoption)
str(adoption)
```


```{r}
# If Geo_code is NA, set it as Geo_unclaimed
# Doing it this way because any other way does not remove 10 NAs 
adoption <- adoption %>% 
  mutate(Geo_Code =  case_when(Geo_Code == "AMER" ~ "AMER",
                               Geo_Code == "EMEA" ~ "EMEA",
                               Geo_Code == "APAC" ~ "APAC",
                               Geo_Code == "JAPN" ~ "JAPN",
                               Geo_Code == "CHNA" ~ "CHNA",
                               Geo_Code == "GLBL" ~ "GLBL",
                               TRUE ~ "GEO-UNCLAIMED"))

```



Calculating customer's age in months based on registration date and storing in a new column on each table
(takes a while to load, but it works!)

```{r}

elapsed_months <- function(end_date, start_date) {
    ed <- as.POSIXlt(end_date)
    sd <- as.POSIXlt(start_date)
    12 * (ed$year - sd$year) + (ed$mon - sd$mon)
}

april$customer_age <- elapsed_months( april$Billing_month, april$Registration_date)

may$customer_age <- elapsed_months( may$Billing_month, may$Registration_date)

june$customer_age <- elapsed_months( june$Billing_month,june$Registration_date)

```

# Replace null product_id with 0

```{r}

april <- sqldf('Select Billing_month, Customer_ID, Registration_date, 
      case when product_id is NULL then 0 else product_id end as product_id,                   Billed_amount, customer_age
               from april')

may <- sqldf('Select Billing_month, Customer_ID, Registration_date, 
      case when product_id is NULL then 0 else product_id end as product_id,                   Billed_amount, customer_age
               from may')

june <- sqldf('Select Billing_month, Customer_ID, Registration_date, 
      case when product_id is NULL then 0 else product_id end as product_id,                   Billed_amount, customer_age
               from june')
```


```{r}
summary(adoption)
```

```{r}
summary(april)
```

```{r}
summary(may)
```

```{r}
summary(june)
```

```{r}
aprilfinish <- april %>%
  group_by(Customer_ID) %>%
  summarise(ProductsUsed = n(), totalBilled = sum(Billed_amount), customer_age = mean(customer_age)) 
mayfinish <- may %>%
  group_by(Customer_ID) %>%
  summarise(ProductsUsed = n(), totalBilled = sum(Billed_amount), customer_age = mean(customer_age))
junefinish <- june %>%
  group_by(Customer_ID) %>%
  summarise(ProductsUsed = n(), totalBilled = sum(Billed_amount), customer_age = mean(customer_age)) 
```




# join table， customer ID as primary key
```{r}
adoptionApril <- adoption %>%
  filter(grepl("April",Month))

AprilAll <- adoptionApril %>% left_join(aprilfinish , c("Customer_ID" = "Customer_ID"))

adoptionMay <- adoption %>%
  filter(grepl("May",Month))
MayAll <- adoptionMay %>% left_join(mayfinish , c("Customer_ID" = "Customer_ID"))

adoptionJune <- adoption %>%
  filter(grepl("June",Month))
JuneAll <-  adoptionJune %>% left_join(junefinish , c("Customer_ID" = "Customer_ID"))

All <- rbind(AprilAll, MayAll, JuneAll)
All$Customer_size <- as.factor(All$Customer_size)
summary(All)



```

# Combine april, may and june billing information

```{r}
combined <- rbind(april, may, june)
```


# Factorize Visualize, Alert and Report into 3 sections

```{r}
All <- All %>%
  mutate(Tools = case_when(Visualize == "Yes" & Alert == "No" & Report == "No" ~ 1,
                           Visualize == "No" & Alert == "Yes" & Report == "No" ~ 2,
                           Visualize == "No" & Alert == "No" & Report == "Yes" ~ 3,
                           Visualize == "Yes" & Alert == "Yes" & Report == "No" ~ 4,
                           Visualize == "Yes" & Alert == "No" & Report == "Yes" ~ 5,
                           Visualize == "No" & Alert == "Yes" & Report == "Yes" ~ 6,
                           Visualize == "Yes" & Alert == "Yes" & Report == "Yes" ~ 7,
                          Visualize == "No" & Alert == "No" & Report == "No" ~ 8))

All$Tools <- as.factor(All$Tools)
```



```{r}

#write.csv(combined, "combined.csv")
#write.csv(All, "All.csv")
#write.csv(adoption, "adoption.csv")

```



